### PR TITLE
Blog app: add API endpoints

### PR DESCRIPTION
**Pull request by username-forGithub**
- Created an API endpoint to:
- list all posts for a user.
- list all comments for a user's post.
- add a comment to a post.
- Added authentication to the API endpoints.

### CODE REVIEW

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 
- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️

- [ ] Good job so far 👏 👏 You've done a great job implementing different API endpoints! In addition to what you have done, I would suggest that you add the API endpoints for authentication, both register and login 😃 As it is among the project requirements. 👇 
image


- Login endpoint - **POST**: `/login`

- Registration endpoint - **POST**: `/register` or `/signup`

Please implement them also to have fully-featured API endpoints 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by username-forGithub** [comment]
Hi, @BertrandConxy ,
There is no requirement in my end
image

**Comment by username-forGithub** [comment]
https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_api_endpoints.md

**Comment by BertrandConxy** [comment]
- [ ] Hello @username-forGithub and @principlebrothers, What they mean by that point  **Add authentication to your API endpoints**  is what I requested that you implement, and from the project guidelines that we as code reviewers use, students are expected to implement the **above-mentioned API endpoints (`/login` and `/register`) as they make up the Authentication. That is why I requested it.** if you need further explanation, please tell me 🙏

**Review by t-yanick — APPROVED** [review]
Hi Team, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by username-forGithub** [comment]
@t-yanick  
Thank you

**Pull request merged**
